version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:25"
      timezone: Europe/Moscow

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:25"
      timezone: Europe/Moscow
