name: test itself
on:
  schedule:
    - cron: "*/10 * * * *" # Каждую среду в 00:00
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Upgrade dependencies
        run: |
          yarn
          yarn add react

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Обновление зависимостей
          title: Обновление зависимостей
          body: |
            Описание изменений:
          labels: dependencies
          branch: upgrade--dependencies
