name: Обновление зависимостей @csssr/e2e-tools
on:
  schedule:
    - cron: 0 0 * * 3 # Каждую среду в 00:00

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Upgrade vega-ui dependencies
        working-directory: "/"
        run: |
          yarn
          yarn upgrade
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Обновление vega-ui
          title: Обновление vega-ui
          body: |
            Описание изменений

          labels: dependencies
          branch: upgrade-vega-ui-dependencies
